#Volumes

configs:
  volume: ./configs

keystore:
  volume: ./keystore

node:
  ip: 34.141.166.196
  name: "name.of.my.node"

execution:
  statsAddress: ethstats.l16.d.lukso.dev
  verbosity: 3
  etherbase: "0x7781121fd00A009670E31b76A2bf99b3A2D6878D"
  dataVolume: ./data/execution_data
  networkId: 19051978
  bootnode: enode://45f5c9d2bec9253f82f44a385692f22a69fdddb5bc5ada29176c3e5977d659529387770e77548dcaad668ce0ef0c74f994ca61a0d55bdfbdffb3813b98c3f7ea@34.91.62.48:30303

consensus:
  statsAddress: 35.202.229.165:9090
  verbosity: info
  version: v0.1.4-dev
  dataVolume: ./data/consensus_data
  bootnode: enr:-MK4QEkSFE8VA-mbzlHLCgyfpvfh7gFPs1AQNrLxNtHSMq58ChKNtwDz7hVkW8qYUGs71tmSeP1buAGJYYZvj_Hp_8yGAX8tWHtih2F0dG5ldHOIAAAAAAAAAACEZXRoMpC3QoawYgAAcf__________gmlkgnY0gmlwhCJ2PI-Jc2VjcDI1NmsxoQMOCac5xZmiy984EK04FgtH-ijxkjdvcXZZvayai71U94hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A

validator:
  dataVolume: ./data/validator_data

ports:
  geth:
    httpPort: 8545
    peerPort: 30303


